services:
  - type: web
    name: trmnl-fbi-most-wanted
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Install wget for cron job
      apt-get update && apt-get install -y wget ca-certificates
    startCommand: gunicorn src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8080
      - key: TRMNL_API_KEY
        sync: false
      - key: TRMNL_PLUGIN_UUID
        sync: false
      - key: CACHE_TIMEOUT
        value: 600
      - key: REFRESH_INTERVAL
        value: 900

  - type: cron
    name: trmnl-fbi-refresh
    env: python
    schedule: "*/5 * * * *"  # Run every 5 minutes
    buildCommand: pip install -r requirements.txt
    startCommand: |
      # Robust wget command with retry and proper SSL handling
      wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 3 \
           --no-check-certificate \
           -qO- https://trmnl-fbi-most-wanted.onrender.com/webhook || \
      curl -k -L --retry 3 --retry-delay 1 --retry-max-time 30 \
           https://trmnl-fbi-most-wanted.onrender.com/webhook
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        fromService:
          name: trmnl-fbi-most-wanted
          type: web
          envVarKey: PORT
      - key: SSL_CERT_FILE
        value: /etc/ssl/certs/ca-certificates.crt
      - key: PYTHONWARNINGS
        value: "ignore:Unverified HTTPS request"