name: FBI Most Wanted TRMNL Update

permissions:
  contents: write

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-display:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate FBI Most Wanted Content
      run: python update_trmnl.py
      env:
        TRMNL_API_KEY: ${{ secrets.TRMNL_API_KEY }}
        TRMNL_PLUGIN_UUID: ${{ secrets.TRMNL_PLUGIN_UUID }}
        
    - name: Commit wanted.jpg
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add wanted.jpg
        git commit -m "Update wanted.jpg"
        git push
        
    - name: Commit QR code
      run: |
        git add qr.jpg
        git commit -m "Update QR code"
        git push
        
    - name: Commit data file
      run: |
        git add FBIMostWanted.json
        git commit -m "Update FBI data"
        git push