name: Update FBI Wanted Data

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-fbi-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run FBI data sync
      env:
        TRMNL_PLUGIN_UUID: ${{ secrets.TRMNL_PLUGIN_UUID }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python main.py
      
    - name: Commit and push updated files
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        
        # Add files only if they exist
        if [ -f qr_code.png ]; then
          git add qr_code.png
        fi
        if [ -f profile_image.jpg ]; then
          git add profile_image.jpg
        fi
        
        # Try to commit if there are changes
        git status --porcelain | grep -q . && git commit -m "Update QR code and profile image" && git push || echo "No changes to commit"